<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Asignacion.aspx.cs" Inherits="Asignacion" Culture="auto" UICulture="auto" Theme="Theme1" EnableSessionState="True" MasterPageFile="~/MasterPage.master"%>


<%@ Register Assembly="LiquidacionWebControls" Namespace="SigametLiquidacion.WebControls" TagPrefix="cc2" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc2" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
    

<asp:Content ID="MainContent" ContentPlaceHolderID="MainPlaceHolder" runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <script type="text/jscript" src="Scripts/MiscControlFunctions.js"></script><script type="text/jscript" src="Scripts/MiscFunctions.js"></script>
  
    
 <asp:UpdatePanel ID="UpdatePanel1" runat="server" >
  <ContentTemplate> 
 <div style="text-align:center; height:650px; width:1100px; vertical-align:top;">
    <table style="background-color:#e1f8e2; height:200px; width:500px;">
       <tr>
            <td class="EtiquetaCelulaRuta" style="width:200px;">
            Usuarios
            </td>
            <td class="EtiquetaCelulaRuta" style="width:170px;">
                Células
            </td >
       </tr>
       
        <tr>
            <td style="vertical-align:top;">
            <div style="overflow:scroll; vertical-align:top;">                    
            <asp:TreeView ID="tvUsuarios" runat="server" AutoGenerateDataBindings="False" 
                    SkinID="CTreeView" Width="130px" 
                    onselectednodechanged="tvUsuarios_SelectedNodeChanged" Font-Bold="True" 
                    ForeColor="#009999" ImageSet="News" BackColor="#E1F8E2">
            </asp:TreeView>
            </div>
            </td>
            <td align="left" valign="top">
                       
                 <table style="background-color:#e1f8e2;">
                    <tr>
                        <td>
                             <asp:Label ID="lblUsuario" runat="server" CssClass="labeltipopago" 
                                        Text="Usuario"></asp:Label>
                        </td>
                        <td>
                        <asp:TextBox ID="txtUsuario" runat="server" CssClass="textboxcaptura"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="rfvUsuario" runat="server" 
                                                        ControlToValidate="txtUsuario" Display="None" 
                                                        ErrorMessage="Seleccione un Usuario" 
                                 ValidationGroup="Guarda"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td>
                        
                        <asp:Label ID="lblCelula" runat="server" CssClass="labeltipopago" 
                                        Text="Celula:"></asp:Label>
                             
                        </td>
                        <td>
                        <asp:DropDownList ID="ddlCelulas" runat="server"  
                     Font-Size="Smaller" CssClass="ContentLitros"/>
                       
                       </td>
                    </tr>
                    <tr>
                        <td>
                             &nbsp;</td>
                        <td>
                       
                            &nbsp;</td>
                    </tr>
                   </table>
                    <tr>
                        <td>
                        </td>
                        <td>
            <asp:ImageButton ID="imbAceptar" runat="server" 
                onclick="imbAceptar_Click" 
                SkinID="btnAceptar" ValidationGroup="Guarda"/>               
                        </td>
                    </tr>
                    <tr>
                        <td>
                            &nbsp;</td>
                        <td>
                            <asp:Label ID="lblError" runat="server" CssClass="labeltipopago" 
                                ForeColor="Red"></asp:Label>
                        </td>
                    </tr>           
             <tr>
             <td class="EtiquetaCelulaRuta" colspan="2">
                Asignados
             </td>
             </tr>
             <tr>
             <td align="center" colspan="2">
                <div style="overflow:scroll;">
                    <asp:GridView ID="gvRelacionUsuarioRuta" runat="server" 
                        AutoGenerateColumns="False"
                        DataKeyNames="AsignacionLiquidacion" 
                        onselectedindexchanged="gvRelacionUsuarioRuta_SelectedIndexChanged">
                        <Columns>
                            <asp:BoundField DataField="TipoAsignacion" HeaderText="Asignacion" />
                            <asp:BoundField DataField="GrupoAsignado" HeaderText="Grupo Asignado" />
                            <asp:BoundField DataField="Celula" HeaderText="Celula" />
                            <asp:BoundField DataField="Descripcion" HeaderText="Descripcion" />
                            <asp:CommandField SelectText="Borrar" ShowSelectButton="True">
                                <ItemStyle ForeColor="Black" HorizontalAlign="Center" />
                            </asp:CommandField>
                            <asp:BoundField DataField="AsignacionLiquidacion" 
                                HeaderText="AsignacionLiquidacion" Visible="False" />
                        </Columns>
                        
                        <RowStyle CssClass="RowStyle" />
                        <PagerStyle CssClass="PagerStyle" />
                        <SelectedRowStyle CssClass="SelectedRowStyle" />
                        <HeaderStyle CssClass="HeaderStyle" />
                        <EditRowStyle CssClass="EditRowStyle" />
                        <AlternatingRowStyle CssClass="AltRowStyle" />
                    </asp:GridView>
                </div>
             </td>
             </tr>
                
            </td>
            </tr>
        
    </table>
</div>
</ContentTemplate>
</asp:UpdatePanel>
     
</asp:Content>
<asp:Content ID="Content1" runat="server" contentplaceholderid="head">
  
   
   
    </asp:Content>

