<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Boletin.aspx.cs" Inherits="Boletin" Theme="Theme1" MasterPageFile="~/MasterPage.master"%>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc2" %>

<%@ Register Assembly="LiquidacionWebControls" Namespace="SigametLiquidacion.WebControls"
    TagPrefix="cc1" %>
    
<asp:Content ID="MainContent" ContentPlaceHolderID="MainPlaceHolder" runat="server">

    <div style="text-align:center">
        <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
        <table style="text-align:left">
            <tr>
                <td>
                    <table>
                        <tr>
                            <td style="font-family:Tahoma;font-size:large;font-weight:bold">
                                <asp:Image ID="Image1" runat="server" ImageUrl="~/Images/sms.png" />
                                Boletines
                            </td>
                        </tr>
                    </table>
                </td>
                <td>
                    <asp:ImageButton id="btnEnviarBoletin" runat="server" 
                        AlternateText="Enviar Boletín" ImageUrl="~/Images/send_sms.png"/>                   
                    <asp:ImageButton ID="btnLlamadaOperador" runat="server" 
                        ImageUrl="~/Images/handset.png" />
                    <asp:ImageButton ID="btnConfirmacionCliente" runat="server" 
                        ImageUrl="~/Images/verify_mark.png" />
                    <asp:ImageButton ID="btnConsultarUsuario" runat="server" 
                        ImageUrl="~/Images/userinfo.png" />
                    <asp:ImageButton ID="btnRefresh" runat="server" 
                        ImageUrl="~/Images/refresh.png" />                   
                </td>
            </tr>
            <tr>
                <td valign="top">
                    <asp:UpdatePanel ID="UpdatePanel2" runat="server">
                        <ContentTemplate>
                            <table>
                                <tr>
                                    <td class="HeaderMainStyle">Ruta:</td>
                                </tr>
                                <tr>
                                    <td>
                                        <asp:Panel ID="pnlFechaRuta" runat="server">                                   
                                            <div style="padding:5px; cursor: pointer; vertical-align: middle; height: 22px;">
                                            <div style="float: left; vertical-align:middle">
                                                <asp:Label ID="lblTagFecha" runat="server" Text="Fecha:"></asp:Label>
                                            </div>
                                            <div style="float: left; margin-left: 10px;">
                                                <asp:TextBox ID="txtFAsignacion" runat="server" Text="" CssClass="calendarTextBox" Enabled="false"></asp:TextBox>
                                            </div>
                                            <div style="float: left; vertical-align: middle">
                                                <asp:ImageButton runat="Server" ID="btnCalFAsignacion" ImageUrl="~/images/Calendar_scheduleHS.png" AlternateText="Click to show calendar" />
                                            </div>
                                            <div style="float: right;">
                                                <asp:ImageButton ID="btnCargaRutas" runat="server" Height="16px" 
                                                    ImageUrl="~/Images/search_start.png" AlternateText="Consultar rutas" 
                                                    onclick="btnCargaRutas_Click"/>
                                            </div>
                                                <cc2:CalendarExtender ID="txtFAsignacion_CalendarExtender" runat="server" 
                                                    TargetControlID="txtFAsignacion" Format="dd/MM/yyyy" PopupButtonID="btnCalFAsignacion">
                                                </cc2:CalendarExtender>
                                            </div>                                            
                                        </asp:Panel>
                                        <asp:Panel ID="Panel2" runat="server">
                                            <asp:TreeView ID="tvRutas" runat="server" 
                                                AutoGenerateDataBindings="False" 
                                                SkinID="CTreeView"
                                                Width="71%">
                                            </asp:TreeView>
                                        </asp:Panel>
                                    </td>
                                </tr>
                            </table>
                        </ContentTemplate>
                    </asp:UpdatePanel>
                </td>
                <td valign="top">
                    <table>
                        <tr>
                            <td>
                                <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                                    <ContentTemplate>
                                        <cc1:ListaPedidos ID="ListaPedidos1" runat="server" 
                                            ImageButtonURL="~/images/edit.jpg" onclickbtnclickme="ListaPedidos1_Click"
                                            ConfigFile="~/configListaBoletin.xml" 
                                            TipoOperacion="Boletin"/>
                                    </ContentTemplate>
                                </asp:UpdatePanel>        
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>       
    <br />
    <div>
    <cc2:ModalPopupExtender ID="mdlPopup" runat="server" TargetControlID="btnEnviarBoletin" PopupControlID="pnlWindowBoletin"
        CancelControlID="btnCancelar" BackgroundCssClass="modalBackground"></cc2:ModalPopupExtender>
    <asp:Panel ID="pnlWindowBoletin" runat="server" style="display:none;" 
        CssClass="modalPopup">
        <table>
            <tr>
                <td colspan="2">
                    Envío de boletín al operador
                </td>
            </tr>
            <tr>
                <td class="leftElements tagCliente">
                    Cliente:
                </td>
                <td class="rightElements Cliente">
                    1013775 - Prueba
                </td>
            </tr>
            <tr>
                <td class="leftElements tagDireccion">
                    Dirección:
                </td>
                <td class="rightElements Direccion">
                    Av San José No. 8, San Juan Ixhuatepec, Tlalnepantla, México.
                </td>
            </tr>
            <tr>
                <td class="leftElements tagCelula">
                    Célula:
                </td>
                <td class="rightElements Celula">
                    1
                </td>
            </tr>
            <tr>
                <td class="leftElements tagRuta">
                    Ruta:
                </td>
                <td class="rightElements Ruta">
                    2
                </td>
            </tr>
            <tr>
                <td class="leftElements tagPedido">
                    Pedido:
                </td>
                <td class="rightElements Pedido">
                    20082888542
                </td>
            </tr>
            <tr>
                <td class="leftElements tagAutotanque">
                    Autotanque:
                </td>
                <td class="rightElements Autotanque">
                    <asp:DropDownList ID="DropDownList1" runat="server">
                        <asp:ListItem>53</asp:ListItem>
                        <asp:ListItem>127</asp:ListItem>                            
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td class="leftElements tagOperador">
                    Operador:
                </td>
                <td class="rightElements Operador">
                    1427 Operador 1
                </td>
            </tr>
            <tr>
                <td class="leftElements tagTelefono">
                    Teléfono asignado:</td>
                <td class="rightElements Telefono">
                    57151464    
                </td>
            </tr>
        </table>
        <div style="text-align: right; width: 100%; margin-top: 5px;">
            <asp:ImageButton ID="btnAceptar" runat="server" SkinID="btnAceptar"/>
            <asp:ImageButton ID="btnCancelar" runat="server" SkinID="btnCancelar"/>
        </div>
    </asp:Panel>
    
    <cc2:ModalPopupExtender ID="mdlPopUpLlamada1" runat="server" TargetControlID="btnLlamadaOperador" PopupControlID="pnlWindowLlamada"
        CancelControlID="btnCancelar1" BackgroundCssClass="modalBackground"></cc2:ModalPopupExtender>
    <asp:Panel ID="pnlWindowLlamada" runat="server" style="display:none;" 
        CssClass="modalPopup">
        <table>
            <tr>
                <td colspan="2">
                    Envío de boletín al operador
                </td>
            </tr>
            <tr>
                <td class="leftElements tagCliente">
                    Cliente:
                </td>
                <td class="rightElements Cliente">
                    1013775 - Prueba
                </td>
            </tr>
            <tr>
                <td class="leftElements tagDireccion">
                    Dirección:
                </td>
                <td class="rightElements Direccion">
                    Av San José No. 8, San Juan Ixhuatepec, Tlalnepantla, México.
                </td>
            </tr>
            <tr>
                <td class="leftElements tagCelula">
                    Célula:
                </td>
                <td class="rightElements Celula">
                    1
                </td>
            </tr>
            <tr>
                <td class="leftElements tagRuta">
                    Ruta:
                </td>
                <td class="rightElements Ruta">
                    2
                </td>
            </tr>
            <tr>
                <td class="leftElements tagPedido">
                    Pedido:
                </td>
                <td class="rightElements Pedido">
                    20082888542
                </td>
            </tr>
            <tr>
                <td class="leftElements tagAutotanque">
                    Autotanque:
                </td>
                <td class="rightElements Autotanque">
                    <asp:DropDownList ID="DropDownList2" runat="server">
                        <asp:ListItem>53</asp:ListItem>
                        <asp:ListItem>127</asp:ListItem>                            
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td class="leftElements tagOperador">
                    Operador:
                </td>
                <td class="rightElements Operador">
                    1427 Operador 1
                </td>
            </tr>
            <tr>
                <td class="leftElements tagTelefono">
                    Teléfono asignado:</td>
                <td class="rightElements Telefono">
                    57151464    
                </td>
            </tr>
        </table>
        <div style="text-align: right; width: 100%; margin-top: 5px;">
            <asp:ImageButton ID="btnAceptar1" runat="server" SkinID="btnAceptar"/>
            <asp:ImageButton ID="btnCancelar1" runat="server" SkinID="btnCancelar"/>
        </div>
    </asp:Panel>
    
    <cc2:ModalPopupExtender ID="mdlPopUpLlamada2" runat="server" TargetControlID="btnConfirmacionCliente" PopupControlID="pnlWindowConfirmacion"
        CancelControlID="btnCancelar2" BackgroundCssClass="modalBackground"></cc2:ModalPopupExtender>
    <asp:Panel ID="pnlWindowConfirmacion" runat="server" style="display:none;" 
        CssClass="modalPopup">
        <table>
            <tr>
                <td colspan="2">
                    Envío de boletín al operador
                </td>
            </tr>
            <tr>
                <td class="leftElements tagCliente">
                    Cliente:
                </td>
                <td class="rightElements Cliente">
                    1013775 - Prueba
                </td>
            </tr>
            <tr>
                <td class="leftElements tagDireccion">
                    Dirección:
                </td>
                <td class="rightElements Direccion">
                    Av San José No. 8, San Juan Ixhuatepec, Tlalnepantla, México.
                </td>
            </tr>
            <tr>
                <td class="leftElements tagCelula">
                    Célula:
                </td>
                <td class="rightElements Celula">
                    1
                </td>
            </tr>
            <tr>
                <td class="leftElements tagRuta">
                    Ruta:
                </td>
                <td class="rightElements Ruta">
                    2
                </td>
            </tr>
            <tr>
                <td class="leftElements tagPedido">
                    Pedido:
                </td>
                <td class="rightElements Pedido">
                    20082888542
                </td>
            </tr>
            <tr>
                <td class="leftElements tagAutotanque">
                    Autotanque:
                </td>
                <td class="rightElements Autotanque">
                    <asp:DropDownList ID="DropDownList3" runat="server">
                        <asp:ListItem>53</asp:ListItem>
                        <asp:ListItem>127</asp:ListItem>                            
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td class="leftElements tagOperador">
                    Operador:
                </td>
                <td class="rightElements Operador">
                    1427 Operador 1
                </td>
            </tr>
            <tr>
                <td class="leftElements tagTelefono">
                    Teléfono asignado:</td>
                <td class="rightElements Telefono">
                    57151464    
                </td>
            </tr>
        </table>
        <div style="text-align: right; width: 100%; margin-top: 5px;">
            <asp:ImageButton ID="btnAceptar2" runat="server" SkinID="btnAceptar"/>
            <asp:ImageButton ID="btnCancelar2" runat="server" SkinID="btnCancelar"/>
        </div>
    </asp:Panel>
    </div>
</asp:Content>