<%@ Page Language="C#" AutoEventWireup="true" CodeFile="LiquidacionesActivas.aspx.cs" Inherits="LiquidacionesActivas" Culture="auto" UICulture="auto" Theme="Theme1" EnableSessionState="True" MasterPageFile="~/MasterPage.master"%>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
    
<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainPlaceHolder" runat="server">

    <script type="text/javascript" language="javascript">       
    var ModalProgress ='<%= ModalProgress.ClientID %>';        
 </script>  
 <script src="Scripts/jsUpdateProgress.js" type="text/javascript"></script>
 
 <asp:ScriptManager ID="ScriptManager1" runat="server">
 </asp:ScriptManager>
 
 <asp:UpdatePanel ID="UpdatePanel1" runat="server" >
  <ContentTemplate>   
 <div style="text-align:center; height:650px; width:1100px; vertical-align:top;">
    <table style="background-color:#e1f8e2; height:200px; width:500px;">
       <tr>
            <td class="EtiquetaCelulaRuta" style="width:200px;">
            Usuarios
            </td>
           
            <td class="EtiquetaCelulaRuta">
                Liquidaciones Activas</td>
       </tr>
       <tr>
            <td style="width:200px; vertical-align:top;">
            <div style=" height:400px; overflow:scroll;">                    
            <asp:TreeView ID="tvUsuarios" runat="server" AutoGenerateDataBindings="False" 
                     SkinID="CTreeView"
                    Width="150px" 
                    onselectednodechanged="tvUsuarios_SelectedNodeChanged" BackColor="#e1f8e2" 
                    Font-Bold="True" ForeColor="#009999" ImageSet="News">
                <SelectedNodeStyle Font-Bold="True" Font-Overline="False" 
                    Font-Underline="True" />
            </asp:TreeView>
            </div>
            </td>
          
            <td align="left" valign="top">
                             
                <asp:GridView ID="gvLiquidacionesActivas" runat="server" 
                    AutoGenerateColumns="False" 
                    DataKeyNames="AñoAtt" 
                    onselectedindexchanged="gvLiquidacionesActivas_SelectedIndexChanged" 
                    AllowPaging="True" 
                    
                    onpageindexchanging="gvLiquidacionesActivas_PageIndexChanging">
                    <Columns>
                        <asp:BoundField DataField="Folio" HeaderText="Folio" />
                        <asp:BoundField DataField="Status" HeaderText="Status"/>
                        <asp:BoundField DataField="AñoAtt" HeaderText="Descripcion" Visible="false"/>
                        <asp:CommandField SelectText="" ShowSelectButton="True" 
                            SelectImageUrl="~/Images/imgTerminar.png" ButtonType="Image">
                            <ItemStyle ForeColor="Black" HorizontalAlign="Center" />
                        </asp:CommandField>
                    </Columns>
                   
                    <RowStyle CssClass="RowStyle" />
                   
                    <PagerStyle BackColor="#E1F8E2" BorderColor="#006666" BorderStyle="Solid" 
                        Font-Bold="False" ForeColor="Black" HorizontalAlign="Center" Wrap="True" />
                   
                    <SelectedRowStyle CssClass="SelectedRowStyle" />
                    <HeaderStyle CssClass="HeaderStyle" />
                    <EditRowStyle CssClass="EditRowStyle" />
                    <AlternatingRowStyle CssClass="AltRowStyle" />
                </asp:GridView>
           
            </td>
        </tr>
       <tr>
       <td>
       <asp:Label ID="lblError" runat="server" CssClass="labeltipopago" ForeColor="Red"></asp:Label>
       </td>
       </tr>
        </table>
</div>
</ContentTemplate>
</asp:UpdatePanel>
<table style="background-color:Transparent">    
      <tr>
      <td>           
         
                            <asp:Panel runat="server" ID="panelUpdateProgress">
                       <asp:UpdateProgress ID="UpdateProgress1" runat="server" AssociatedUpdatePanelID="UpdatePanel1" > 
                                                <ProgressTemplate>
                                             <%--<asp:Panel runat="server" ID="PanelUpdate">--%>
                                                            <img alt="" src="Images/updateProgress.gif"/><b>  Procesando... </b>
                                             <%--   </asp:Panel>--%>
                                                </ProgressTemplate> 
                       </asp:UpdateProgress>
                            </asp:Panel>
                                              <cc1:ModalPopupExtender ID="ModalProgress" runat="server" PopupControlID="panelUpdateProgress" BackgroundCssClass="modalBackground" TargetControlID="panelUpdateProgress">
                                              </cc1:ModalPopupExtender> 
                   
        </td>
        </tr>
</table>
</asp:Content>


